---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cm
data:
  MONGO_SERVICE_HOST: 172.30.38.223
  MONGO_SERVICE_PORT: "27017"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  MONGODB_USER: cm9vdA==
  MONGODB_PASSWORD: cWltaW5mbw==
type: Opaque
